const DEFAULT_SCHEMA="gestion_trabajo";
const PAGE_SIZE=1000;
export interface SupabaseAdminConfig {url:string;secretKey:string;schema:string}
interface SupabaseErrorDiagnostics {responseCode?:string;responseMessage?:string;requestId?:string;clientInstanceId?:number;requestNumber?:number;concurrentRequests?:number}
export class SupabaseMigrationError extends Error {
  readonly operation:string;readonly table:string;readonly httpStatus?:number;
  readonly responseCode?:string;readonly responseMessage?:string;readonly requestId?:string;
  readonly clientInstanceId?:number;readonly requestNumber?:number;readonly concurrentRequests?:number;
  constructor(operation:string,table:string,httpStatus?:number,diagnostics:SupabaseErrorDiagnostics={}){
    super(`Supabase no pudo completar ${operation} en ${table}.`);this.name="SupabaseMigrationError";this.operation=operation;this.table=table;this.httpStatus=httpStatus;
    this.responseCode=diagnostics.responseCode;this.responseMessage=diagnostics.responseMessage;this.requestId=diagnostics.requestId;
    this.clientInstanceId=diagnostics.clientInstanceId;this.requestNumber=diagnostics.requestNumber;this.concurrentRequests=diagnostics.concurrentRequests;
  }
}
export class SupabaseConcurrencyError extends Error {readonly table:string;readonly id:string;constructor(table:string,id:string){super(`El registro ${table}/${id} cambió desde que fue cargado. Recargá antes de guardar.`);this.name="SupabaseConcurrencyError";this.table=table;this.id=id}}
const required=(value:string|undefined,name:string):string=>{if(!value?.trim())throw new Error(`Falta configurar ${name}.`);return value.trim()};
export function getSupabaseAdminConfig(env:NodeJS.ProcessEnv=process.env):SupabaseAdminConfig {if(typeof window!=="undefined")throw new Error("La configuración administrativa de Supabase es exclusiva del servidor.");const rawUrl=required(env.SUPABASE_URL,"SUPABASE_URL").replace(/\/$/,"");const url=new URL(rawUrl);if(url.protocol!=="https:"&&url.hostname!=="localhost"&&url.hostname!=="127.0.0.1")throw new Error("SUPABASE_URL debe usar HTTPS.");const schema=env.SUPABASE_SCHEMA?.trim()||DEFAULT_SCHEMA;if(!/^[a-z_][a-z0-9_]*$/.test(schema))throw new Error("SUPABASE_SCHEMA no es válido.");return{url:url.toString().replace(/\/$/,""),secretKey:required(env.SUPABASE_SECRET_KEY,"SUPABASE_SECRET_KEY"),schema}}
let nextClientInstanceId=0;
export class SupabaseAdminRestClient {
  private readonly config:SupabaseAdminConfig;
  private readonly diagnosticInstanceId=++nextClientInstanceId;
  private requestNumber=0;
  private activeRequests=0;
  constructor(config:SupabaseAdminConfig=getSupabaseAdminConfig()){this.config=config}
  private tableUrl(table:string,query=""):URL{if(!/^[a-z_][a-z0-9_]*$/.test(table))throw new Error("Nombre de tabla no válido.");return new URL(`/rest/v1/${table}${query}`,this.config.url)}
  private headers(write=false):Record<string,string>{return{apikey:this.config.secretKey,Accept:"application/json","Accept-Profile":this.config.schema,...(write?{"Content-Type":"application/json","Content-Profile":this.config.schema}:{})}}
  private safeDiagnostic(value:unknown):string|undefined {if(typeof value!=="string"||!value.trim())return undefined;return value.replaceAll(this.config.secretKey,"[REDACTED]").replace(/Bearer\s+\S+/gi,"Bearer [REDACTED]").slice(0,500)}
  private async errorDiagnostics(response:Response,request?:Pick<SupabaseErrorDiagnostics,"requestNumber"|"concurrentRequests">):Promise<SupabaseErrorDiagnostics>{const payload=await response.clone().json().catch(()=>({})) as Record<string,unknown>;return{responseCode:this.safeDiagnostic(payload.code),responseMessage:this.safeDiagnostic(payload.message),requestId:this.safeDiagnostic(response.headers.get("sb-request-id")??response.headers.get("x-request-id")),clientInstanceId:this.diagnosticInstanceId,...request}}
  private async migrationError(operation:string,table:string,response:Response,request?:Pick<SupabaseErrorDiagnostics,"requestNumber"|"concurrentRequests">):Promise<SupabaseMigrationError>{return new SupabaseMigrationError(operation,table,response.status,await this.errorDiagnostics(response,request))}
  async select<T extends object>(table:string,columns="*"):Promise<T[]>{const rows:T[]=[];for(let offset=0;;offset+=PAGE_SIZE){const requestNumber=++this.requestNumber;const concurrentRequests=++this.activeRequests;try{const response=await fetch(this.tableUrl(table,`?select=${encodeURIComponent(columns)}`),{method:"GET",headers:{...this.headers(),Range:`${offset}-${offset+PAGE_SIZE-1}`},cache:"no-store"});if(!response.ok)throw await this.migrationError("la lectura",table,response,{requestNumber,concurrentRequests});const page=await response.json() as T[];rows.push(...page);if(page.length<PAGE_SIZE)break}finally{this.activeRequests--}}return rows}
  async selectWhere<T extends object>(table:string,columns="*",filters:Record<string,string>={}):Promise<T[]>{const rows:T[]=[];const params=new URLSearchParams({select:columns});for(const [key,value] of Object.entries(filters)){if(value!==undefined&&value!==null&&String(value).trim())params.set(key,String(value));}for(let offset=0;;offset+=PAGE_SIZE){const requestNumber=++this.requestNumber;const concurrentRequests=++this.activeRequests;try{const response=await fetch(this.tableUrl(table,`?${params.toString()}&offset=${offset}&limit=${PAGE_SIZE}`),{method:"GET",headers:{...this.headers(),Range:`${offset}-${offset+PAGE_SIZE-1}`},cache:"no-store"});if(!response.ok)throw await this.migrationError("la lectura filtrada",table,response,{requestNumber,concurrentRequests});const page=await response.json() as T[];rows.push(...page);if(page.length<PAGE_SIZE)break}finally{this.activeRequests--}}return rows}
  async upsert(table:string,rows:Record<string,unknown>[],conflict:string):Promise<void>{if(!rows.length)return;const response=await fetch(this.tableUrl(table,`?on_conflict=${encodeURIComponent(conflict)}`),{method:"POST",headers:{...this.headers(true),Prefer:"resolution=merge-duplicates,return=minimal"},body:JSON.stringify(rows),cache:"no-store"});if(!response.ok)throw await this.migrationError("el upsert",table,response)}
  async insert<T extends Record<string,unknown>>(table:string,row:Record<string,unknown>):Promise<T>{const response=await fetch(this.tableUrl(table),{method:"POST",headers:{...this.headers(true),Prefer:"return=representation"},body:JSON.stringify(row),cache:"no-store"});if(!response.ok)throw await this.migrationError("la creación",table,response);const rows=await response.json() as T[];if(!rows[0])throw new SupabaseMigrationError("la verificación de creación",table);return rows[0]}
  async updateById<T extends Record<string,unknown>>(table:string,id:string,values:Record<string,unknown>,expectedUpdatedAt?:string):Promise<T>{const params=new URLSearchParams({id:`eq.${id}`});if(expectedUpdatedAt)params.set("updated_at",`eq.${expectedUpdatedAt}`);const response=await fetch(this.tableUrl(table,`?${params.toString()}`),{method:"PATCH",headers:{...this.headers(true),Prefer:"return=representation"},body:JSON.stringify(values),cache:"no-store"});if(!response.ok)throw await this.migrationError("la actualización",table,response);const rows=await response.json() as T[];if(!rows[0]){if(expectedUpdatedAt)throw new SupabaseConcurrencyError(table,id);throw new SupabaseMigrationError("la verificación de actualización",table)}return rows[0]}
  async rpc<T>(functionName:string,parameters:Record<string,unknown>):Promise<T>{if(!/^[a-z_][a-z0-9_]*$/.test(functionName))throw new Error("Nombre de RPC no válido.");const response=await fetch(new URL(`/rest/v1/rpc/${functionName}`,this.config.url),{method:"POST",headers:{...this.headers(true),Prefer:"return=representation"},body:JSON.stringify(parameters),cache:"no-store"});if(!response.ok){const diagnostics=await this.errorDiagnostics(response);if(response.status===409||diagnostics.responseCode==="PT409")throw new SupabaseConcurrencyError(functionName,String(parameters.p_id??"registro"));throw new SupabaseMigrationError("la operación transaccional",functionName,response.status,diagnostics)}return await response.json() as T}
  async deleteWhere(table:string,filters:Record<string,string>):Promise<void>{const response=await fetch(this.tableUrl(table,`?${new URLSearchParams(filters).toString()}`),{method:"DELETE",headers:{...this.headers(true),Prefer:"return=minimal"},cache:"no-store"});if(!response.ok)throw await this.migrationError("la eliminación",table,response)}
  async deleteById(table:string,id:string,expectedUpdatedAt?:string):Promise<void>{const filters:Record<string,string>={id:`eq.${id}`};if(expectedUpdatedAt)filters.updated_at=`eq.${expectedUpdatedAt}`;const response=await fetch(this.tableUrl(table,`?${new URLSearchParams(filters).toString()}`),{method:"DELETE",headers:{...this.headers(true),Prefer:"return=representation"},cache:"no-store"});if(!response.ok)throw await this.migrationError("la eliminación",table,response);const rows=await response.json() as Record<string,unknown>[];if(!rows.length&&expectedUpdatedAt)throw new SupabaseConcurrencyError(table,id)}
}
