import { randomUUID } from "node:crypto";
import type { AppData, DeliverableVersion, Initiative, InitiativeBundle, Project, ScheduleBlock, Task, User, WorkPreferences } from "../../types/index.ts";
import { requireProjectAccess, requireProjectManager, requireServerPermission, requireServerPrincipal } from "../auth/authorization.ts";
import { SupabaseWorkspaceStore, type SupabaseRow } from "./workspace-store.ts";

const cleanId=(id:string)=>id.trim()||randomUUID();
const value=(row:SupabaseRow,key:string)=>typeof row[key]==="string"?row[key] as string:"";

export class SupabaseWorkspaceService {
  readonly store:SupabaseWorkspaceStore;
  constructor(store:SupabaseWorkspaceStore=new SupabaseWorkspaceStore()){this.store=store}
  async loadWorkspace(currentUserId?:string):Promise<AppData>{return this.store.load(currentUserId)}
  private async refreshed(){return this.loadWorkspace((await requireServerPrincipal()).appId)}
  private async userByName(name:string){const user=(await this.store.list("profiles")).find(row=>value(row,"name")===name||value(row,"email").toLowerCase()===name.toLowerCase());if(!user)throw new Error("El responsable seleccionado no existe.");return user}
  private async userId(name:string){return value(await this.userByName(name),"id")}
  private async userIds(names:string[]){return Promise.all([...new Set(names)].map(name=>this.userId(name)))}
  private async areaId(projectId:string,name:string){const area=(await this.store.list("areas")).find(row=>value(row,"project_id")===projectId&&value(row,"name")===name);if(!area)throw new Error("El área seleccionada no existe.");return value(area,"id")}
  private async taskControl(task:Task|{projectId:string;assignedProfileId:string}){const principal=await requireProjectAccess(task.projectId,"edit");if(principal.role==="usuario"){const assigned="assignedProfileId" in task?task.assignedProfileId:await this.userId(task.assignedTo);if(assigned!==principal.appId)throw new Error("FORBIDDEN")}return principal}

  async saveProject(project:Project,isNew:boolean){const principal=isNew?await requireServerPermission("manageProjects"):await requireProjectManager(project.id),id=cleanId(project.id),clientId=project.clientId.trim();if(!clientId||!(await this.store.byId("clients",clientId)))throw new Error("Seleccioná un cliente existente antes de crear el proyecto.");const names=[...new Set((project.areas??[project.area]).map(name=>name.trim()).filter(Boolean))],existing=(await this.store.list("areas")).filter(row=>value(row,"project_id")===id),areas=names.map(name=>({id:value(existing.find(row=>value(row,"name")===name)??{},"id")||randomUUID(),name}));await this.store.rpc("save_project_with_areas",{p_record:{id,client_id:clientId,name:project.name,color:project.color,active:project.active,primary_area:project.area},p_areas:areas,p_manager_profile_id:isNew&&principal.role==="gestor"?principal.appId:null,p_expected_updated_at:isNew?null:project.revision??null});return this.refreshed()}
  async deleteProject(id:string){await requireProjectManager(id);const current=await this.store.byId("projects",id);if(!current)throw new Error("El proyecto no existe.");await this.store.delete("projects",id,value(current,"updated_at"));return this.refreshed()}
  async addArea(projectId:string,name:string){await requireProjectManager(projectId);await this.store.insert("areas",{id:randomUUID(),project_id:projectId,name:name.trim(),active:true});return this.refreshed()}

  private async initiativeRow(item:Initiative,isNew:boolean){const owners=await this.userIds([item.owner,...(item.owners??[])]);return{row:{id:isNew?cleanId(item.id):item.id,project_id:item.projectId,area_id:await this.areaId(item.projectId,item.area),name:item.name,description:item.description??null,success_criteria:item.successCriteria??null,status:item.status,start_date:item.startDate,deadline:item.deadline||null,impact:item.impact},owners}}
  async saveInitiative(item:Initiative,isNew:boolean){await requireProjectManager(item.projectId);const {row,owners}=await this.initiativeRow(item,isNew);await this.store.rpc("save_initiative_with_owners",{p_record:row,p_owners:owners.map((profileId,index)=>({profile_id:profileId,is_primary:index===0})),p_expected_updated_at:isNew?null:item.revision??null});return this.refreshed()}
  async deleteInitiative(id:string){const current=await this.store.byId("initiatives",id);if(!current)throw new Error("La iniciativa no existe.");await requireProjectManager(value(current,"project_id"));await this.store.delete("initiatives",id,value(current,"updated_at"));return this.refreshed()}
  private async projectForVersion(item:DeliverableVersion){const initiative=await this.store.byId("initiatives",item.initiativeId);if(!initiative)throw new Error("La iniciativa no existe.");return value(initiative,"project_id")}
  async saveVersion(item:DeliverableVersion,isNew:boolean){await requireProjectManager(await this.projectForVersion(item));const row={id:isNew?cleanId(item.id):item.id,initiative_id:item.initiativeId,code:item.code,name:item.name,status:item.status,owner_profile_id:await this.userId(item.owner),start_date:item.startDate,deadline:item.deadline,validated:Boolean(item.validated)};if(isNew)await this.store.insert("versions",row);else await this.store.update("versions",item.id,row,item.revision);return this.refreshed()}
  async deleteVersion(id:string){const version=await this.store.byId("versions",id);if(!version)throw new Error("La versión no existe.");const initiative=await this.store.byId("initiatives",value(version,"initiative_id"));if(!initiative)throw new Error("La iniciativa no existe.");await requireProjectManager(value(initiative,"project_id"));await this.store.delete("versions",id,value(version,"updated_at"));return this.refreshed()}

  private async taskRow(item:Task,isNew:boolean){return{id:isNew?cleanId(item.id):item.id,project_id:item.projectId,initiative_id:item.initiativeId,version_id:item.versionId,title:item.title,description:item.description,priority:item.priority,status:item.status,deadline:item.deadline,estimated_minutes:item.estimatedMinutes,splittable:item.splittable,progress:item.progress,assigned_profile_id:await this.userId(item.assignedTo)}}
  private async taskRelations(task:Task){const normalized=task.subtasks.map(subtask=>({...subtask,id:cleanId(subtask.id)})),wanted=new Set(normalized.map(subtask=>subtask.id));if(wanted.size!==normalized.length)throw new Error("Hay subtareas duplicadas.");return{subtasks:await Promise.all(normalized.map(async subtask=>({id:subtask.id,title:subtask.title,completed:subtask.completed,completed_at:subtask.completedAt??null,assigned_profile_id:await this.userId(subtask.assignedTo||task.assignedTo)}))),dependencies:[...new Set(task.dependencies)].map(dependsOnTaskId=>({id:randomUUID(),depends_on_task_id:dependsOnTaskId}))}}
  async saveTask(item:Task,isNew:boolean){const assignedProfileId=await this.userId(item.assignedTo);await this.taskControl({projectId:item.projectId,assignedProfileId});if(!isNew){const current=await this.store.byId("tasks",item.id);if(!current)throw new Error("La tarea no existe.");await this.taskControl({projectId:value(current,"project_id"),assignedProfileId:value(current,"assigned_profile_id")})}const row=await this.taskRow(item,isNew),relations=await this.taskRelations(item);await this.store.rpc("save_task_with_relations",{p_record:row,p_subtasks:relations.subtasks,p_dependencies:relations.dependencies,p_expected_updated_at:isNew?null:item.revision??null});return this.refreshed()}
  async deleteTask(id:string){const task=await this.store.byId("tasks",id);if(!task)throw new Error("La tarea no existe.");await this.taskControl({projectId:value(task,"project_id"),assignedProfileId:value(task,"assigned_profile_id")});await this.store.delete("tasks",id,value(task,"updated_at"));return this.refreshed()}
  async toggleSubtask(taskId:string,subtaskId:string){const task=await this.store.byId("tasks",taskId),subtask=await this.store.byId("subtasks",subtaskId);if(!task||!subtask)throw new Error("La tarea o subtarea no existe.");await this.taskControl({projectId:value(task,"project_id"),assignedProfileId:value(task,"assigned_profile_id")});const completed=!subtask.completed;await this.store.update("subtasks",subtaskId,{completed,completed_at:completed?new Date().toISOString():null},value(subtask,"updated_at"));return this.refreshed()}

  async saveBlock(block:ScheduleBlock,isNew:boolean){const principal=await requireServerPermission("manageSchedule"),task=await this.store.byId("tasks",block.taskId);if(!task)throw new Error("La tarea no existe.");await requireProjectAccess(value(task,"project_id"),"view");if(principal.role==="usuario"&&value(task,"assigned_profile_id")!==principal.appId)throw new Error("FORBIDDEN");const row={id:isNew?cleanId(block.id):block.id,profile_id:principal.appId,task_id:block.taskId,plan_date:block.date,start_time:block.startTime||null,end_time:block.endTime||null,source:block.source,outcome:block.outcome??"planned",completed:block.completed,completed_at:block.completedAt??null};if(isNew)await this.store.insert("schedule_blocks",row);else{const current=await this.store.byId("schedule_blocks",block.id);if(!current||value(current,"profile_id")!==principal.appId)throw new Error("El bloque no existe.");await this.store.update("schedule_blocks",block.id,row,block.revision)}return this.refreshed()}
  async deleteBlock(id:string){const principal=await requireServerPermission("manageSchedule"),row=await this.store.byId("schedule_blocks",id);if(!row||value(row,"profile_id")!==principal.appId)throw new Error("El bloque no existe.");await this.store.delete("schedule_blocks",id,value(row,"updated_at"));return this.refreshed()}
  async savePreferences(preferences:WorkPreferences){const principal=await requireServerPermission("manageSchedule"),existing=(await this.store.list("work_preferences")).find(row=>value(row,"profile_id")===principal.appId),row={profile_id:principal.appId,day_start:preferences.dayStart,day_end:preferences.dayEnd,working_days:preferences.workingDays,focus_block_minutes:preferences.focusBlockMinutes};if(existing)await this.store.update("work_preferences",value(existing,"id"),row,preferences.revision);else await this.store.insert("work_preferences",{id:randomUUID(),...row});return this.refreshed()}
  async setBlockOutcome(id:string,outcome:"planned"|"advanced"|"completed"){const principal=await requireServerPermission("manageSchedule"),block=await this.store.byId("schedule_blocks",id);if(!block||value(block,"profile_id")!==principal.appId)throw new Error("El bloque no existe.");const task=await this.store.byId("tasks",value(block,"task_id"));if(!task)throw new Error("La tarea no existe.");await requireProjectAccess(value(task,"project_id"),"view");if(principal.role==="usuario"&&value(task,"assigned_profile_id")!==principal.appId)throw new Error("FORBIDDEN");await this.store.rpc("set_block_outcome",{p_id:id,p_profile_id:principal.appId,p_outcome:outcome,p_expected_updated_at:value(block,"updated_at")});return this.refreshed()}

  async saveUser(user:User,isNew:boolean){const principal=await requireServerPermission("manageUsers"),id=isNew?cleanId(user.id):user.id;if(principal.appId===id&&!user.active)throw new Error("No podés desactivar tu propia cuenta.");const row={id,name:user.name,email:user.email.trim().toLowerCase(),initials:user.initials,role:user.role,manage_users:user.role==="admin",manage_projects:user.role==="admin"||user.role==="gestor",manage_schedule:true,active:user.active,...(isNew?{entra_object_id:null}:{})},members=user.role==="admin"?[]:user.assignedProjectIds.map(projectId=>({id:randomUUID(),project_id:projectId,access_level:user.editableProjectIds?.includes(projectId)?"edit":"view"}));await this.store.rpc("save_profile_with_members",{p_record:row,p_members:members,p_expected_updated_at:isNew?null:user.revision??null});return this.refreshed()}
  async deleteUser(id:string){const principal=await requireServerPermission("manageUsers");if(principal.appId===id)throw new Error("No podés eliminar tu propia cuenta.");const current=await this.store.byId("profiles",id);if(!current)throw new Error("El usuario no existe.");await this.store.delete("profiles",id,value(current,"updated_at"));return this.refreshed()}
  async createInitiativeBundle(bundle:InitiativeBundle){await requireProjectManager(bundle.initiative.projectId);const {row,owners}=await this.initiativeRow(bundle.initiative,true);let versionRow:SupabaseRow|null=null,tasks:SupabaseRow[]=[];if(bundle.version){const version=bundle.version,versionId=cleanId(version.id);versionRow={id:versionId,code:version.code,name:version.name,status:version.status,owner_profile_id:await this.userId(version.owner),start_date:version.startDate,deadline:version.deadline,validated:Boolean(version.validated)};tasks=await Promise.all(bundle.tasks.map(async task=>{const normalized={...task,initiativeId:value(row,"id"),versionId},taskRow=await this.taskRow(normalized,true),relations=await this.taskRelations(normalized);return{...taskRow,subtasks:relations.subtasks,dependencies:relations.dependencies}}))}await this.store.rpc("create_initiative_bundle",{p_initiative:row,p_owners:owners.map((profileId,index)=>({profile_id:profileId,is_primary:index===0})),p_version:versionRow,p_tasks:tasks});return this.refreshed()}
  async saveHierarchy(initiatives:Initiative[],versions:DeliverableVersion[],tasks:Task[]){for(const item of initiatives)await this.saveInitiative(item,false);for(const item of versions)await this.saveVersion(item,false);for(const item of tasks)await this.saveTask(item,false);return this.refreshed()}
}
