"use client";
import { useEffect, useMemo, useState } from "react";
import { useApp } from "@/hooks/use-app";
import { formatDate, initiativeProgress, versionProgress } from "@/lib/format";
import { StatusPill } from "@/components/ui/status-pill";
import { Modal } from "@/components/ui/modal";
import { TaskForm } from "@/components/tasks/task-form";
import { InitiativeForm } from "@/components/initiatives/initiative-form";
import { VersionForm } from "@/components/initiatives/version-form";
import { AreaForm } from "@/components/projects/area-form";
import type { DeliverableVersion, Initiative, Task, TaskStatus } from "@/types";

const statuses:TaskStatus[]=["Pendiente","En curso","En revisión","Completada","Retrasada"];
const owners=["Jazmín","Romina","Iris","Fernando"];

export function Hierarchy({projectId}:{projectId:string}){
  const{data,currentUser,toggleSubtask,saveHierarchy,deleteInitiative,deleteVersion,deleteTask,notice,clearNotice}=useApp();
  const[openI,setOpenI]=useState(new Set<string>()),[openV,setOpenV]=useState(new Set<string>()),[filter,setFilter]=useState("Todas"),[form,setForm]=useState<{i:string;v:string}|null>(null),[editing,setEditing]=useState(false);
  const[draftI,setDraftI]=useState<Initiative[]>([]),[draftV,setDraftV]=useState<DeliverableVersion[]>([]),[draftT,setDraftT]=useState<Task[]>([]);
  const[initiativeForm,setInitiativeForm]=useState(false),[versionForm,setVersionForm]=useState<string|null>(null),[areaForm,setAreaForm]=useState(false);
  useEffect(()=>{if(!notice)return;const timer=setTimeout(clearNotice,3200);return()=>clearTimeout(timer)},[notice,clearNotice]);
  useEffect(()=>{if(!editing)return;const warn=(event:BeforeUnloadEvent)=>{event.preventDefault()};window.addEventListener("beforeunload",warn);return()=>window.removeEventListener("beforeunload",warn)},[editing]);
  const sourceI=editing?draftI:data.initiatives,sourceV=editing?draftV:data.versions,sourceT=editing?draftT:data.tasks;
  const all=sourceI.filter(i=>i.projectId===projectId),project=data.projects.find(p=>p.id===projectId),areas=["Todas",...new Set([...(project?.areas??[]),...all.map(i=>i.area)])],items=all.filter(i=>filter==="Todas"||i.area===filter),canEdit=currentUser?.role==="admin"||currentUser?.editableProjectIds?.includes(projectId);
  const draftData=useMemo(()=>({...data,initiatives:sourceI,versions:sourceV,tasks:sourceT}),[data,sourceI,sourceV,sourceT]);
  const toggle=(set:Set<string>,id:string,update:(x:Set<string>)=>void)=>{const n=new Set(set);if(n.has(id))n.delete(id);else n.add(id);update(n)};
  const startEditing=()=>{const projectInitiatives=data.initiatives.filter(i=>i.projectId===projectId);const ids=new Set(projectInitiatives.map(i=>i.id));const versions=data.versions.filter(v=>ids.has(v.initiativeId));setDraftI(structuredClone(projectInitiatives));setDraftV(structuredClone(versions));setDraftT(structuredClone(data.tasks.filter(t=>t.projectId===projectId)));setEditing(true)};
  const cancel=()=>{setEditing(false);setDraftI([]);setDraftV([]);setDraftT([])};
  const save=()=>{saveHierarchy(draftI,draftV,draftT);setEditing(false)};
  const updateI=(id:string,field:keyof Initiative,value:string)=>setDraftI(list=>list.map(i=>i.id===id?{...i,[field]:value}:i));
  const updateV=(id:string,field:keyof DeliverableVersion,value:string)=>setDraftV(list=>list.map(v=>v.id===id?{...v,[field]:value}:v));
  const updateT=(id:string,field:keyof Task,value:Task[keyof Task])=>setDraftT(list=>list.map(t=>t.id===id?{...t,[field]:value}:t));
  const moveTask=(id:string,versionId:string)=>{const version=draftV.find(v=>v.id===versionId);if(version)setDraftT(list=>list.map(t=>t.id===id?{...t,versionId,initiativeId:version.initiativeId}:t))};
  return <>
    <section className="areas"><div className="section-title"><h2>Áreas</h2><div className="section-actions"><span>Solo funcionan como filtros</span>{canEdit&&<button className="link-button" onClick={()=>setAreaForm(true)}>+ Nueva área</button>}</div></div><div className="filters">{areas.map(a=><button key={a} className={filter===a?"active":""} onClick={()=>setFilter(a)}>{a}</button>)}</div></section>
    <section><div className="list-title hierarchy-title"><div><h2>Iniciativas</h2><p>Esta es la tabla maestra. Sus cambios se reflejan en pendientes y agenda.</p></div><div className="master-actions"><span>{items.length} resultados</span>{canEdit&&(editing?<><button className="button quiet compact" onClick={cancel}>Cancelar</button><button className="button primary compact" onClick={save}>Guardar cambios</button></>:<><button className="button quiet compact" onClick={startEditing}>Editar</button><button className="button primary compact" onClick={()=>setInitiativeForm(true)}>+ Iniciativa</button></>)}</div></div>
      {editing&&<div className="editing-banner"><span>Modo edición</span><p>Podés modificar iniciativas, versiones y tareas directamente en la tabla.</p></div>}
      <div className={editing?"hierarchy-wrap editing-master":"hierarchy-wrap"}><div className="hierarchy-table"><div className="hierarchy-head"><span>Iniciativa / versión</span><span>Avance</span><span>Responsable</span><span>Inicio</span><span>Fecha límite</span><span>Estado</span><span>Impacto</span></div>
      {items.length?items.map(i=><article className="entity" key={i.id}>{editing?<InitiativeEditRow item={i} data={draftData} update={updateI} open={openI.has(i.id)} onToggle={()=>toggle(openI,i.id,setOpenI)} onDelete={()=>{if(confirm(`¿Eliminar la iniciativa ${i.name} y todo su contenido?`)){deleteInitiative(i.id);cancel()}}}/>:<div className="entity-row"><EntityName open={openI.has(i.id)} onToggle={()=>toggle(openI,i.id,setOpenI)} title={i.name} subtitle={`${i.area} · ${i.versionIds.length} versiones`}/><Progress value={initiativeProgress(i,data)}/><Owner name={i.owner}/><span>{formatDate(i.startDate)}</span><span>{formatDate(i.deadline)}</span><span><StatusPill value={i.status}/></span><span className="impact">{i.impact}</span></div>}
        {openI.has(i.id)&&<div className="versions">{sourceV.filter(v=>v.initiativeId===i.id).map(v=><div key={v.id}>{editing?<VersionEditRow item={v} data={draftData} update={updateV} open={openV.has(v.id)} onToggle={()=>toggle(openV,v.id,setOpenV)} onDelete={()=>{if(confirm(`¿Eliminar la versión ${v.name} y sus tareas?`)){deleteVersion(v.id);cancel()}}}/>:<div className="entity-row version-row"><div className="entity-name indent"><button className={openV.has(v.id)?"chev open":"chev"} onClick={()=>toggle(openV,v.id,setOpenV)}>›</button><span className="version-code">{v.code}</span><div><b>{v.name}</b><small>{v.taskIds.length} tareas</small></div></div><Progress value={versionProgress(v.id,data)}/><Owner name={v.owner}/><span>{formatDate(v.startDate)}</span><span>{formatDate(v.deadline)}</span><span><StatusPill value={v.status}/></span><span className="muted-cell">Heredado</span></div>}
          {openV.has(v.id)&&<div className="subtasks-block task-master"><div className="subtask-head"><span></span><span>Tarea</span><span>Responsable</span><span>{editing?"Fecha / estado":"Avance"}</span></div>{sourceT.filter(t=>t.versionId===v.id).map(t=>editing?<TaskEditRow key={t.id} item={t} tasks={draftT} versions={draftV} update={updateT} move={moveTask} onDelete={()=>{if(confirm(`¿Eliminar la tarea ${t.title}?`)){deleteTask(t.id);cancel()}}}/>:<div className={t.status==="Completada"?"subtask-row done":"subtask-row"} key={t.id}><input type="checkbox" checked={t.status==="Completada"} onChange={()=>t.subtasks[0]&&toggleSubtask(t.id,t.subtasks[0].id)}/><span>{t.title}<small>{t.priority} · {t.estimatedMinutes} min{t.dependencies.length?` · depende de ${t.dependencies.length}`:""}</small></span><Owner name={t.assignedTo}/><span>{t.progress}%</span></div>)}{canEdit&&<button className="add-subtask" onClick={()=>setForm({i:i.id,v:v.id})}>+ Nueva tarea</button>}</div>}
        </div>)}{canEdit&&<button className="add-version" onClick={()=>setVersionForm(i.id)}>+ Nueva versión</button>}</div>}
      </article>):<div className="empty"><b>No hay iniciativas en esta área.</b><span>Elegí otro filtro para ver resultados.</span></div>}</div></div>
    </section>
    {notice&&<div className="toast" role="status">{notice}</div>}
    <Modal open={!!form} onClose={()=>setForm(null)} title="Nueva tarea">{form&&<TaskForm projectId={projectId} initiativeId={form.i} versionId={form.v} onDone={()=>setForm(null)}/>}</Modal>
    <Modal open={initiativeForm} onClose={()=>setInitiativeForm(false)} title="Nueva iniciativa"><InitiativeForm defaultProjectId={projectId} onDone={()=>setInitiativeForm(false)}/></Modal>
    <Modal open={!!versionForm} onClose={()=>setVersionForm(null)} title="Nueva versión">{versionForm&&<VersionForm initiativeId={versionForm} onDone={()=>setVersionForm(null)}/>}</Modal>
    <Modal open={areaForm} onClose={()=>setAreaForm(false)} title="Nueva área"><AreaForm projectId={projectId} onDone={()=>setAreaForm(false)}/></Modal>
  </>
}

function EntityName({open,onToggle,title,subtitle}:{open:boolean;onToggle:()=>void;title:string;subtitle:string}){return <div className="entity-name"><button className={open?"chev open":"chev"} onClick={onToggle}>›</button><div><b>{title}</b><small>{subtitle}</small></div></div>}
function Progress({value}:{value:number}){return <span className="progress"><i><b style={{width:`${value}%`}}/></i><strong>{value}%</strong></span>}
function Owner({name}:{name:string}){return <span className="owner"><i>{name.slice(0,2).toUpperCase()}</i>{name}</span>}
function InitiativeEditRow({item,data,update,open,onToggle,onDelete}:{item:Initiative;data:ReturnType<typeof useApp>["data"];update:(id:string,f:keyof Initiative,v:string)=>void;open:boolean;onToggle:()=>void;onDelete:()=>void}){return <div className="entity-row inline-edit-row"><div className="editable-tree-cell"><button className={open?"chev open":"chev"} onClick={onToggle}>›</button><div className="edit-name-stack"><input value={item.name} onChange={e=>update(item.id,"name",e.target.value)}/><input className="micro-input" value={item.area} onChange={e=>update(item.id,"area",e.target.value)}/></div><button className="inline-delete" onClick={onDelete} aria-label="Eliminar iniciativa">×</button></div><Progress value={initiativeProgress(item,data)}/><Select value={item.owner} options={owners} onChange={v=>update(item.id,"owner",v)}/><input type="date" value={item.startDate} onChange={e=>update(item.id,"startDate",e.target.value)}/><input type="date" value={item.deadline} onChange={e=>update(item.id,"deadline",e.target.value)}/><Select value={item.status} options={statuses} onChange={v=>update(item.id,"status",v)}/><Select value={item.impact} options={["Alto","Medio","Bajo"]} onChange={v=>update(item.id,"impact",v)}/></div>}
function VersionEditRow({item,data,update,open,onToggle,onDelete}:{item:DeliverableVersion;data:ReturnType<typeof useApp>["data"];update:(id:string,f:keyof DeliverableVersion,v:string)=>void;open:boolean;onToggle:()=>void;onDelete:()=>void}){return <div className="entity-row version-row inline-edit-row"><div className="editable-tree-cell indent"><button className={open?"chev open":"chev"} onClick={onToggle}>›</button><div className="version-edit-name"><input className="code-input" value={item.code} onChange={e=>update(item.id,"code",e.target.value)}/><input value={item.name} onChange={e=>update(item.id,"name",e.target.value)}/></div><button className="inline-delete" onClick={onDelete} aria-label="Eliminar versión">×</button></div><Progress value={versionProgress(item.id,data)}/><Select value={item.owner} options={owners} onChange={v=>update(item.id,"owner",v)}/><input type="date" value={item.startDate} onChange={e=>update(item.id,"startDate",e.target.value)}/><input type="date" value={item.deadline} onChange={e=>update(item.id,"deadline",e.target.value)}/><Select value={item.status} options={statuses} onChange={v=>update(item.id,"status",v)}/><span className="muted-cell">Heredado</span></div>}
function TaskEditRow({item,tasks,versions,update,move,onDelete}:{item:Task;tasks:Task[];versions:DeliverableVersion[];update:(id:string,f:keyof Task,v:Task[keyof Task])=>void;move:(id:string,v:string)=>void;onDelete:()=>void}){const setSubtasks=(subtasks:Task["subtasks"])=>{const progress=subtasks.length?Math.round(subtasks.filter(s=>s.completed).length/subtasks.length*100):item.progress;update(item.id,"subtasks",subtasks);update(item.id,"progress",progress)};return <div className="subtask-row task-edit-row"><input type="checkbox" checked={item.status==="Completada"} onChange={e=>update(item.id,"status",e.target.checked?"Completada":"Pendiente")}/><div className="task-edit-name"><div className="task-title-delete"><input value={item.title} onChange={e=>update(item.id,"title",e.target.value)}/><button className="inline-delete" onClick={onDelete} aria-label="Eliminar tarea">×</button></div><input className="task-description-input" value={item.description} onChange={e=>update(item.id,"description",e.target.value)} placeholder="Agregar contexto…"/><div><Select value={item.priority} options={["Alta","Media","Baja"]} onChange={v=>update(item.id,"priority",v)}/><input type="number" min="15" step="15" value={item.estimatedMinutes} onChange={e=>update(item.id,"estimatedMinutes",Number(e.target.value))}/><span>min</span><label className="split-inline"><input type="checkbox" checked={item.splittable} onChange={e=>update(item.id,"splittable",e.target.checked)}/> Divisible</label></div><div className="task-relations"><label>Versión<select value={item.versionId} onChange={e=>move(item.id,e.target.value)}>{versions.map(v=><option key={v.id} value={v.id}>{v.code} · {v.name}</option>)}</select></label><label>Depende de<select value={item.dependencies[0]??""} onChange={e=>update(item.id,"dependencies",e.target.value?[e.target.value]:[])}><option value="">Sin dependencia</option>{tasks.filter(t=>t.id!==item.id).map(t=><option key={t.id} value={t.id}>{t.title}</option>)}</select></label></div><div className="task-subtasks-editor">{item.subtasks.map(s=><div key={s.id}><input type="checkbox" checked={s.completed} onChange={()=>setSubtasks(item.subtasks.map(x=>x.id===s.id?{...x,completed:!x.completed}:x))}/><input value={s.title} onChange={e=>setSubtasks(item.subtasks.map(x=>x.id===s.id?{...x,title:e.target.value}:x))}/><button onClick={()=>setSubtasks(item.subtasks.filter(x=>x.id!==s.id))}>×</button></div>)}<button onClick={()=>setSubtasks([...item.subtasks,{id:`s-${Date.now()}`,title:"Nueva subtarea",completed:false,assignedTo:item.assignedTo}])}>+ Subtarea</button></div></div><Select value={item.assignedTo} options={owners} onChange={v=>update(item.id,"assignedTo",v)}/><div className="task-date-status"><input type="date" value={item.deadline} onChange={e=>update(item.id,"deadline",e.target.value)}/><Select value={item.status} options={statuses} onChange={v=>update(item.id,"status",v)}/></div></div>}
function Select({value,options,onChange}:{value:string;options:readonly string[];onChange:(v:string)=>void}){return <select value={value} onChange={e=>onChange(e.target.value)}>{options.map(o=><option key={o}>{o}</option>)}</select>}
