"use server";
import{randomUUID}from"node:crypto";import type{AppData,DeliverableVersion,Initiative,InitiativeBundle,Project,ScheduleBlock,Task,User,WorkPreferences}from"@/types";import{requireProjectAccess,requireProjectManager,requireServerPermission,requireServerPrincipal}from"@/services/auth/authorization";import{SharePointCrudRepositories}from"@/services/sharepoint/crud-repository";import{SharePointRelationshipCrud}from"@/services/sharepoint/relationship-crud";import{readSharePointWorkspace}from"@/services/sharepoint/workspace-reader";
const repos=()=>new SharePointCrudRepositories(),cleanId=(id:string)=>id.trim()||randomUUID(),message=()=>"No se pudo guardar el cambio en SharePoint.";
export async function loadWorkspace():Promise<AppData>{const principal=await requireServerPrincipal(),result=await readSharePointWorkspace(undefined,principal.appId);if(!result.data)throw new Error("No se pudo cargar el espacio de trabajo.");return result.data}
async function refreshed(){return loadWorkspace()}
async function userByName(r:SharePointCrudRepositories,name:string){const user=(await r.users.list()).find(item=>item.name===name||item.email.toLowerCase()===name.toLowerCase());if(!user)throw new Error("El responsable seleccionado no existe.");return user}
async function userIdByName(r:SharePointCrudRepositories,name:string){return(await userByName(r,name)).id}
async function userIdsByNames(r:SharePointCrudRepositories,names:string[]){return Promise.all([...new Set(names)].map(name=>userIdByName(r,name)))}
async function areaIdByName(r:SharePointCrudRepositories,projectId:string,name:string){const area=(await r.areas.list()).find(item=>item.projectId===projectId&&item.name===name);if(!area)throw new Error("El área seleccionada no existe.");return area.id}
async function requireTaskControl(r:SharePointCrudRepositories,task:Task|{projectId:string;assignedUserId:string}){const principal=await requireProjectAccess(task.projectId,"edit");if(principal.role==="usuario"){const assignedUserId="assignedUserId"in task?task.assignedUserId:await userIdByName(r,task.assignedTo);if(assignedUserId!==principal.appId)throw new Error("FORBIDDEN")}return principal}

export async function saveProjectAction(project:Project,isNew:boolean){const principal=isNew?await requireServerPermission("manageProjects"):await requireProjectManager(project.id),r=repos(),value={...project,id:cleanId(project.id),clientId:cleanId(project.clientId)};if(isNew){if(!(await r.clients.getByAppId(value.clientId)))await r.clients.create({id:value.clientId,name:value.name});await r.projects.create(value);if(principal.role==="gestor")await r.projectMembers.create({id:randomUUID(),projectId:value.id,userId:principal.appId,accessLevel:"edit"})}else{const current=await r.projects.getByAppId(value.id);if(!current)throw new Error(message());await r.projects.update(value,current.eTag)}const desired=new Set(value.areas??[value.area]),existing=(await r.areas.listVersioned()).filter(item=>item.entity.projectId===value.id);for(const name of desired){const found=existing.find(item=>item.entity.name===name);if(!found)await r.areas.create({id:randomUUID(),projectId:value.id,name,active:true});else if(!found.entity.active)await r.areas.update({...found.entity,active:true},found.eTag)}for(const area of existing.filter(item=>!desired.has(item.entity.name)&&item.entity.name!==value.area&&item.entity.active))await r.areas.update({...area.entity,active:false},area.eTag);return refreshed()}
export async function deleteProjectAction(id:string){await requireProjectManager(id);const r=repos();await new SharePointRelationshipCrud(r).deleteProject(id);return refreshed()}
export async function addAreaAction(projectId:string,name:string){await requireProjectManager(projectId);const r=repos();await r.areas.create({id:randomUUID(),projectId,name:name.trim(),active:true});return refreshed()}

async function buildInitiativeRecord(r:SharePointCrudRepositories,item:Initiative,isNew:boolean){const ownerUserIds=await userIdsByNames(r,[item.owner,...(item.owners??[])]);return{id:isNew?cleanId(item.id):item.id,projectId:item.projectId,areaId:await areaIdByName(r,item.projectId,item.area),name:item.name,description:item.description,successCriteria:item.successCriteria,status:item.status,ownerUserId:ownerUserIds[0],ownerUserIds,startDate:item.startDate,deadline:item.deadline,impact:item.impact}}
export async function saveInitiativeAction(item:Initiative,isNew:boolean){await requireProjectManager(item.projectId);const r=repos(),record=await buildInitiativeRecord(r,item,isNew);if(isNew)await r.initiatives.create(record);else{const current=await r.initiatives.getByAppId(record.id);if(!current)throw new Error(message());await r.initiatives.update(record,current.eTag)}return refreshed()}
export async function deleteInitiativeAction(id:string){const r=repos(),current=await r.initiatives.getByAppId(id);if(!current)throw new Error(message());await requireProjectManager(current.entity.projectId);await new SharePointRelationshipCrud(r).deleteInitiative(id,current.eTag);return refreshed()}
async function projectForVersion(r:SharePointCrudRepositories,version:DeliverableVersion){const initiative=await r.initiatives.getByAppId(version.initiativeId);if(!initiative)throw new Error(message());return initiative.entity.projectId}
export async function saveVersionAction(item:DeliverableVersion,isNew:boolean){const r=repos();await requireProjectManager(await projectForVersion(r,item));const record={id:isNew?cleanId(item.id):item.id,initiativeId:item.initiativeId,code:item.code,name:item.name,status:item.status,ownerUserId:await userIdByName(r,item.owner),startDate:item.startDate,deadline:item.deadline};if(isNew)await r.versions.create(record);else{const current=await r.versions.getByAppId(record.id);if(!current)throw new Error(message());await r.versions.update(record,current.eTag)}return refreshed()}
export async function deleteVersionAction(id:string){const r=repos(),version=await r.versions.getByAppId(id);if(!version)throw new Error(message());const initiative=await r.initiatives.getByAppId(version.entity.initiativeId);if(!initiative)throw new Error(message());await requireProjectManager(initiative.entity.projectId);await new SharePointRelationshipCrud(r).deleteVersion(id,version.eTag);return refreshed()}

export async function saveTaskAction(item:Task,isNew:boolean){const r=repos(),assignedUserId=await userIdByName(r,item.assignedTo);await requireTaskControl(r,{projectId:item.projectId,assignedUserId});const record={id:isNew?cleanId(item.id):item.id,projectId:item.projectId,initiativeId:item.initiativeId,versionId:item.versionId,title:item.title,description:item.description,priority:item.priority,status:item.status,deadline:item.deadline,estimatedMinutes:item.estimatedMinutes,splittable:item.splittable,progress:item.progress,assignedUserId};if(!isNew){const current=await r.tasks.getByAppId(record.id);if(!current)throw new Error(message());await requireTaskControl(r,current.entity);await r.tasks.update(record,current.eTag)}else await r.tasks.create(record);const subtasks=(await r.subtasks.listVersioned()).filter(row=>row.entity.taskId===record.id),wanted=new Set(item.subtasks.map(row=>row.id));for(const subtask of item.subtasks){const current=subtasks.find(row=>row.entity.id===subtask.id),entity={id:cleanId(subtask.id),taskId:record.id,title:subtask.title,completed:subtask.completed,completedAt:subtask.completedAt,assignedUserId:await userIdByName(r,subtask.assignedTo||item.assignedTo)};if(current)await r.subtasks.update(entity,current.eTag);else await r.subtasks.create(entity)}for(const stale of subtasks.filter(row=>!wanted.has(row.entity.id)))await r.subtasks.delete(stale.entity.id,stale.eTag);return refreshed()}
export async function deleteTaskAction(id:string){const r=repos(),task=await r.tasks.getByAppId(id);if(!task)throw new Error(message());await requireTaskControl(r,task.entity);await new SharePointRelationshipCrud(r).deleteTask(id,task.eTag);return refreshed()}
export async function saveHierarchyAction(initiatives:Initiative[],versions:DeliverableVersion[],tasks:Task[]){let result:AppData|undefined;for(const item of initiatives)result=await saveInitiativeAction(item,false);for(const item of versions)result=await saveVersionAction(item,false);for(const item of tasks)result=await saveTaskAction(item,false);return result??refreshed()}
export async function toggleSubtaskAction(taskId:string,subtaskId:string){const r=repos(),task=await r.tasks.getByAppId(taskId),subtask=await r.subtasks.getByAppId(subtaskId);if(!task||!subtask)throw new Error(message());await requireTaskControl(r,task.entity);const completed=!subtask.entity.completed;await r.subtasks.update({...subtask.entity,completed,completedAt:completed?new Date().toISOString():undefined},subtask.eTag);return refreshed()}

export async function saveBlockAction(block:ScheduleBlock,isNew:boolean){const principal=await requireServerPermission("manageSchedule"),r=repos(),task=await r.tasks.getByAppId(block.taskId);if(!task)throw new Error(message());await requireProjectAccess(task.entity.projectId,"view");if(principal.role==="usuario"&&task.entity.assignedUserId!==principal.appId)throw new Error("FORBIDDEN");const record={...block,id:isNew?cleanId(block.id):block.id,userId:principal.appId};if(isNew)await r.scheduleBlocks.create(record);else{const current=await r.scheduleBlocks.getByAppId(record.id);if(!current||current.entity.userId!==principal.appId)throw new Error(message());await r.scheduleBlocks.update(record,current.eTag)}return refreshed()}
export async function deleteBlockAction(id:string){const principal=await requireServerPermission("manageSchedule"),r=repos(),current=await r.scheduleBlocks.getByAppId(id);if(!current||current.entity.userId!==principal.appId)throw new Error(message());await r.scheduleBlocks.delete(id,current.eTag);return refreshed()}
export async function savePreferencesAction(value:WorkPreferences){const principal=await requireServerPermission("manageSchedule"),r=repos(),existing=(await r.workPreferences.listVersioned()).find(item=>item.entity.userId===principal.appId),record={id:existing?.entity.id??randomUUID(),userId:principal.appId,...value};if(existing)await r.workPreferences.update(record,existing.eTag);else await r.workPreferences.create(record);return refreshed()}
export async function setBlockOutcomeAction(id:string,outcome:"planned"|"advanced"|"completed"){const principal=await requireServerPermission("manageSchedule"),r=repos(),block=await r.scheduleBlocks.getByAppId(id);if(!block||block.entity.userId!==principal.appId)throw new Error(message());const task=await r.tasks.getByAppId(block.entity.taskId);if(!task)throw new Error(message());await requireProjectAccess(task.entity.projectId,"view");if(principal.role==="usuario"&&task.entity.assignedUserId!==principal.appId)throw new Error("FORBIDDEN");const completed=outcome==="completed";await r.scheduleBlocks.update({...block.entity,outcome,completed,completedAt:completed?new Date().toISOString():undefined},block.eTag);if(outcome==="advanced"&&task.entity.status==="Pendiente")await r.tasks.update({...task.entity,status:"En curso"},task.eTag);if(completed){const latest=await r.tasks.getByAppId(task.entity.id);if(latest)await r.tasks.update({...latest.entity,status:"Completada",progress:100},latest.eTag);const future=(await r.scheduleBlocks.listVersioned()).filter(item=>item.entity.userId===principal.appId&&item.entity.taskId===task.entity.id&&item.entity.date>block.entity.date);for(const item of future)await r.scheduleBlocks.delete(item.entity.id,item.eTag)}return refreshed()}

export async function saveUserAction(user:User,isNew:boolean){const principal=await requireServerPermission("manageUsers"),r=repos();let value={...user,id:isNew?cleanId(user.id):user.id,email:user.email.trim().toLowerCase(),entraObjectId:isNew?undefined:user.entraObjectId,permissions:{manageUsers:user.role==="admin",manageProjects:user.role==="admin"||user.role==="gestor",manageSchedule:true}};if(principal.appId===value.id&&!value.active)throw new Error("No podés desactivar tu propia cuenta.");if(isNew)await r.users.create(value);else{const current=await r.users.getByAppId(value.id);if(!current)throw new Error(message());value={...value,entraObjectId:current.entity.entraObjectId};await r.users.update(value,current.eTag)}const existing=(await r.projectMembers.listVersioned()).filter(item=>item.entity.userId===value.id);for(const member of existing)await r.projectMembers.delete(member.entity.id,member.eTag);if(value.role!=="admin")for(const projectId of value.assignedProjectIds)await r.projectMembers.create({id:randomUUID(),projectId,userId:value.id,accessLevel:value.editableProjectIds?.includes(projectId)?"edit":"view"});return refreshed()}
export async function deleteUserAction(id:string){const principal=await requireServerPermission("manageUsers");if(principal.appId===id)throw new Error("No podés eliminar tu propia cuenta.");const r=repos();await new SharePointRelationshipCrud(r).deleteUser(id);return refreshed()}
export async function createInitiativeBundleAction(bundle:InitiativeBundle){await requireProjectManager(bundle.initiative.projectId);const r=repos(),created=await buildInitiativeRecord(r,bundle.initiative,true);await r.initiatives.create(created);if(bundle.version){const version=bundle.version,versionRecord={id:cleanId(version.id),initiativeId:created.id,code:version.code,name:version.name,status:version.status,ownerUserId:await userIdByName(r,version.owner),startDate:version.startDate,deadline:version.deadline};await r.versions.create(versionRecord);for(const task of bundle.tasks)await r.tasks.create({id:cleanId(task.id),projectId:task.projectId,initiativeId:created.id,versionId:versionRecord.id,title:task.title,description:task.description,priority:task.priority,status:task.status,deadline:task.deadline,estimatedMinutes:task.estimatedMinutes,splittable:task.splittable,progress:task.progress,assignedUserId:await userIdByName(r,task.assignedTo)})}return refreshed()}
